package com.ysten.local.bss.bsstv.repository.mapper;

import com.ysten.local.bss.bsstv.domain.RecCategory;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RecCategoryMapper {



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_category
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int deleteByPrimaryKey(Long catgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_category
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int insert(RecCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_category
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int insertSelective(RecCategory record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_category
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	RecCategory selectByPrimaryKey(Long catgId);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_category
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int updateByPrimaryKeySelective(RecCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_category
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int updateByPrimaryKey(RecCategory record);

    int getTotalCount(@Param("cateId")Long cateId,@Param("categoryName")String categoryName);

    List<RecCategory> findCategoryList(@Param("cateId")Long cateId,@Param("categoryName")String categoryName, @Param("pageNo")Integer pageNo, @Param("pageSize")Integer pageSize);
}