package com.ysten.local.bss.bsstv.repository.mapper;

import com.ysten.local.bss.bsstv.domain.RecProgramContentOperate;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RecProgramContentOperateMapper {



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_program_content_operate
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int deleteByPrimaryKey(Long programId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_program_content_operate
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int insert(RecProgramContentOperate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_program_content_operate
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int insertSelective(RecProgramContentOperate record);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_program_content_operate
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	RecProgramContentOperate selectByPrimaryKey(Long programId);




	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_program_content_operate
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int updateByPrimaryKeySelective(RecProgramContentOperate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_program_content_operate
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(RecProgramContentOperate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rec_program_content_operate
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	int updateByPrimaryKey(RecProgramContentOperate record);

    List<RecProgramContentOperate> findProgramContentList(@Param("programId")Long programId,@Param("programName")String programName,@Param("pageNo")Integer pageNo,@Param("pageSize")Integer pageSize);

    int getTotalCount(@Param("programId")Long programId,@Param("programName")String programName);
}