package com.ysten.local.bss.logger.domain;

import java.util.Date;

public class DeviceOperateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_device_operate_log.id
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_device_operate_log.device_code
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    private String deviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_device_operate_log.ip
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_device_operate_log.status
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_device_operate_log.create_date
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_device_operate_log.result
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_device_operate_log.id
     *
     * @return the value of bss_device_operate_log.id
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_device_operate_log.id
     *
     * @param id the value for bss_device_operate_log.id
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_device_operate_log.device_code
     *
     * @return the value of bss_device_operate_log.device_code
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_device_operate_log.device_code
     *
     * @param deviceCode the value for bss_device_operate_log.device_code
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_device_operate_log.ip
     *
     * @return the value of bss_device_operate_log.ip
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_device_operate_log.ip
     *
     * @param ip the value for bss_device_operate_log.ip
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_device_operate_log.status
     *
     * @return the value of bss_device_operate_log.status
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_device_operate_log.status
     *
     * @param status the value for bss_device_operate_log.status
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_device_operate_log.create_date
     *
     * @return the value of bss_device_operate_log.create_date
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_device_operate_log.create_date
     *
     * @param createDate the value for bss_device_operate_log.create_date
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_device_operate_log.result
     *
     * @return the value of bss_device_operate_log.result
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_device_operate_log.result
     *
     * @param result the value for bss_device_operate_log.result
     *
     * @mbggenerated Tue Jul 08 14:16:53 CST 2014
     */
    public void setResult(String result) {
        this.result = result;
    }
}