delete from bss_device_vendor;
delete from bss_device_upgrade;
delete from bss_platform_version;
delete from bss_device_rule;
delete from bss_platform;
delete from bss_device_type;
delete from bss_device;
delete from bss_customer;
delete from bss_account;