package com.ysten.local.bss.panel.domain;

import com.ysten.local.bss.util.bean.Required;

import java.io.Serializable;
import java.util.Date;

public class PanelPanelItemMap extends BaseDomain {
    private static final long serialVersionUID = -816129400080575307L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column bss_panel_panel_item_map.id
     *
     * @mbggenerated Fri May 23 16:04:16 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column bss_panel_panel_item_map.panel_id
     *
     * @mbggenerated Fri May 23 16:04:16 CST 2014
     */
    @Required
    private Long panelId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column bss_panel_panel_item_map.panel_item_id
     *
     * @mbggenerated Fri May 23 16:04:16 CST 2014
     */
    @Required
    private Long panelItemId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column bss_panel_panel_item_map.sort_num
     *
     * @mbggenerated Fri May 23 16:04:16 CST 2014
     */
    @Required
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column bss_panel_panel_item_map.rel_type
     *
     * @mbggenerated Fri May 23 16:04:16 CST 2014
     */
    private Integer relType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column bss_panel_panel_item_map.status
     *
     * @mbggenerated Fri May 23 16:04:16 CST 2014
     */
    private Integer status;

    // REL_ID,适配用
    private Long relId;

    // epg_rel_id
    private Long epgRelId;

    private Long epgPanelId;

    private Long epgPanelitemId;
    // //兼容epg
    private Date createTime;
    // 兼容epg
    private Long userId;
    // 兼容epg
    private Date statusTime;

    private String districtCode;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPanelId() {
        return panelId;
    }

    public void setPanelId(Long panelId) {
        this.panelId = panelId;
    }

    public Long getPanelItemId() {
        return panelItemId;
    }

    public void setPanelItemId(Long panelItemId) {
        this.panelItemId = panelItemId;
    }

    public Integer getSortNum() {
        return sortNum;
    }

    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    public Integer getRelType() {
        return relType;
    }

    public void setRelType(Integer relType) {
        this.relType = relType;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getEpgPanelId() {
        return epgPanelId;
    }

    public void setEpgPanelId(Long epgPanelId) {
        this.epgPanelId = epgPanelId;
    }

    public Long getEpgPanelitemId() {
        return epgPanelitemId;
    }

    public void setEpgPanelitemId(Long epgPanelitemId) {
        this.epgPanelitemId = epgPanelitemId;
    }

    public Long getEpgRelId() {
        return epgRelId;
    }

    public void setEpgRelId(Long epgRelId) {
        this.epgRelId = epgRelId;
    }

    public Long getRelId() {
        return relId;
    }

    public void setRelId(Long relId) {
        this.relId = relId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Date getStatusTime() {
        return statusTime;
    }

    public void setStatusTime(Date statusTime) {
        this.statusTime = statusTime;
    }

    public String getDistrictCode() {
        return districtCode;
    }

    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }
}