package com.ysten.local.bss.bsstv.domain;

import java.io.Serializable;
import java.util.Date;

public class RecCategory implements Serializable{

	private static final long serialVersionUID = -5226868465274914587L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.CATG_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long catgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.FID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long fid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.Grade
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.Type
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.Name
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.FDNCode
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String fdncode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.CATG_ALIAS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String catgAlias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.TITLE_NAME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String titleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.PARENT_CATG_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long parentCatgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.CATG_NUMBER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Integer catgNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.ACTION_TYPE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String actionTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.ACTION_LINK
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String actionLink;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.SUB_STYLE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String subStyleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.CATG_TYPE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String catgTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.INNER_PIC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String innerPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.OUT_PIC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String outPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.STATUS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.CATG_DESC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String catgDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.CITE_CATG_ITEM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long citeCatgItemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.CREATE_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.CREATE_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.LAST_MODIFY_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Date lastModifyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.LAST_MODIFY_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String lastModifyUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.SHOW_SUM
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Integer showSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category.ASSORTMENT_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String assortmentId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.CATG_ID
	 * @return  the value of rec_category.CATG_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getCatgId() {
		return catgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.CATG_ID
	 * @param catgId  the value for rec_category.CATG_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCatgId(Long catgId) {
		this.catgId = catgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.FID
	 * @return  the value of rec_category.FID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getFid() {
		return fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.FID
	 * @param fid  the value for rec_category.FID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setFid(Long fid) {
		this.fid = fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.Grade
	 * @return  the value of rec_category.Grade
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.Grade
	 * @param grade  the value for rec_category.Grade
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setGrade(Long grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.Type
	 * @return  the value of rec_category.Type
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.Type
	 * @param type  the value for rec_category.Type
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.Name
	 * @return  the value of rec_category.Name
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.Name
	 * @param name  the value for rec_category.Name
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.FDNCode
	 * @return  the value of rec_category.FDNCode
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getFdncode() {
		return fdncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.FDNCode
	 * @param fdncode  the value for rec_category.FDNCode
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setFdncode(String fdncode) {
		this.fdncode = fdncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.CATG_ALIAS
	 * @return  the value of rec_category.CATG_ALIAS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getCatgAlias() {
		return catgAlias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.CATG_ALIAS
	 * @param catgAlias  the value for rec_category.CATG_ALIAS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCatgAlias(String catgAlias) {
		this.catgAlias = catgAlias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.TITLE_NAME
	 * @return  the value of rec_category.TITLE_NAME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getTitleName() {
		return titleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.TITLE_NAME
	 * @param titleName  the value for rec_category.TITLE_NAME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setTitleName(String titleName) {
		this.titleName = titleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.PARENT_CATG_ID
	 * @return  the value of rec_category.PARENT_CATG_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getParentCatgId() {
		return parentCatgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.PARENT_CATG_ID
	 * @param parentCatgId  the value for rec_category.PARENT_CATG_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setParentCatgId(Long parentCatgId) {
		this.parentCatgId = parentCatgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.CATG_NUMBER
	 * @return  the value of rec_category.CATG_NUMBER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Integer getCatgNumber() {
		return catgNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.CATG_NUMBER
	 * @param catgNumber  the value for rec_category.CATG_NUMBER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCatgNumber(Integer catgNumber) {
		this.catgNumber = catgNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.ACTION_TYPE_ID
	 * @return  the value of rec_category.ACTION_TYPE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getActionTypeId() {
		return actionTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.ACTION_TYPE_ID
	 * @param actionTypeId  the value for rec_category.ACTION_TYPE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setActionTypeId(String actionTypeId) {
		this.actionTypeId = actionTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.ACTION_LINK
	 * @return  the value of rec_category.ACTION_LINK
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getActionLink() {
		return actionLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.ACTION_LINK
	 * @param actionLink  the value for rec_category.ACTION_LINK
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setActionLink(String actionLink) {
		this.actionLink = actionLink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.SUB_STYLE_ID
	 * @return  the value of rec_category.SUB_STYLE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getSubStyleId() {
		return subStyleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.SUB_STYLE_ID
	 * @param subStyleId  the value for rec_category.SUB_STYLE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setSubStyleId(String subStyleId) {
		this.subStyleId = subStyleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.CATG_TYPE_ID
	 * @return  the value of rec_category.CATG_TYPE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getCatgTypeId() {
		return catgTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.CATG_TYPE_ID
	 * @param catgTypeId  the value for rec_category.CATG_TYPE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCatgTypeId(String catgTypeId) {
		this.catgTypeId = catgTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.INNER_PIC
	 * @return  the value of rec_category.INNER_PIC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getInnerPic() {
		return innerPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.INNER_PIC
	 * @param innerPic  the value for rec_category.INNER_PIC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setInnerPic(String innerPic) {
		this.innerPic = innerPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.OUT_PIC
	 * @return  the value of rec_category.OUT_PIC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getOutPic() {
		return outPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.OUT_PIC
	 * @param outPic  the value for rec_category.OUT_PIC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setOutPic(String outPic) {
		this.outPic = outPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.STATUS
	 * @return  the value of rec_category.STATUS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.STATUS
	 * @param status  the value for rec_category.STATUS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.CATG_DESC
	 * @return  the value of rec_category.CATG_DESC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getCatgDesc() {
		return catgDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.CATG_DESC
	 * @param catgDesc  the value for rec_category.CATG_DESC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCatgDesc(String catgDesc) {
		this.catgDesc = catgDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.CITE_CATG_ITEM_ID
	 * @return  the value of rec_category.CITE_CATG_ITEM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getCiteCatgItemId() {
		return citeCatgItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.CITE_CATG_ITEM_ID
	 * @param citeCatgItemId  the value for rec_category.CITE_CATG_ITEM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCiteCatgItemId(Long citeCatgItemId) {
		this.citeCatgItemId = citeCatgItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.CREATE_TIME
	 * @return  the value of rec_category.CREATE_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.CREATE_TIME
	 * @param createTime  the value for rec_category.CREATE_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.CREATE_USER
	 * @return  the value of rec_category.CREATE_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.CREATE_USER
	 * @param createUser  the value for rec_category.CREATE_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.LAST_MODIFY_DATE
	 * @return  the value of rec_category.LAST_MODIFY_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Date getLastModifyDate() {
		return lastModifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.LAST_MODIFY_DATE
	 * @param lastModifyDate  the value for rec_category.LAST_MODIFY_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.LAST_MODIFY_USER
	 * @return  the value of rec_category.LAST_MODIFY_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getLastModifyUser() {
		return lastModifyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.LAST_MODIFY_USER
	 * @param lastModifyUser  the value for rec_category.LAST_MODIFY_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setLastModifyUser(String lastModifyUser) {
		this.lastModifyUser = lastModifyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.SHOW_SUM
	 * @return  the value of rec_category.SHOW_SUM
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Integer getShowSum() {
		return showSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.SHOW_SUM
	 * @param showSum  the value for rec_category.SHOW_SUM
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setShowSum(Integer showSum) {
		this.showSum = showSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category.ASSORTMENT_ID
	 * @return  the value of rec_category.ASSORTMENT_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getAssortmentId() {
		return assortmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category.ASSORTMENT_ID
	 * @param assortmentId  the value for rec_category.ASSORTMENT_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setAssortmentId(String assortmentId) {
		this.assortmentId = assortmentId;
	}
}