package com.ysten.local.bss.bsstv.domain;

import java.io.Serializable;
import java.util.Date;

public class RecCategoryProgram implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1231121229631483811L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category_program.ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category_program.CATG_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long catgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category_program.PROGRAM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long programId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category_program.CREATE_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_category_program.CREATE_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String createUser;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category_program.ID
	 * @return  the value of rec_category_program.ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category_program.ID
	 * @param id  the value for rec_category_program.ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category_program.CATG_ID
	 * @return  the value of rec_category_program.CATG_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getCatgId() {
		return catgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category_program.CATG_ID
	 * @param catgId  the value for rec_category_program.CATG_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCatgId(Long catgId) {
		this.catgId = catgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category_program.PROGRAM_ID
	 * @return  the value of rec_category_program.PROGRAM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getProgramId() {
		return programId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category_program.PROGRAM_ID
	 * @param programId  the value for rec_category_program.PROGRAM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setProgramId(Long programId) {
		this.programId = programId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category_program.CREATE_TIME
	 * @return  the value of rec_category_program.CREATE_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category_program.CREATE_TIME
	 * @param createTime  the value for rec_category_program.CREATE_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_category_program.CREATE_USER
	 * @return  the value of rec_category_program.CREATE_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_category_program.CREATE_USER
	 * @param createUser  the value for rec_category_program.CREATE_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}
}