package com.ysten.local.bss.bsstv.domain;

import java.io.Serializable;
import java.util.Date;

public class RecProgramContentOperate implements Serializable{

	private static final long serialVersionUID = 5800669124736455347L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PROGRAM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long programId;

    private Long categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PROGRAM_NAME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String programName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.ENGLISH_NAME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String englishName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.ALIAS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.MATERIAL_TYPE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String materialTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.MATERIAL_CLASS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String materialClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.DEFINITION_CODE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String definitionCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.ZONE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String zone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.DIRECTOR
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String director;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.LEADING_ROLE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String leadingRole;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.YEARS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String years;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.LANGUAGE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long languageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.SET_NUMBER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long setNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.BITRATE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Integer bitrateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.TRIAL_DURA
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long trialDura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PROGRAM_STATUS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String programStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.RESOLUTION_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Integer resolutionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PROGRAM_LENGTH
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Integer programLength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.TAG
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PREMIERE_CHANNEL_UUID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String premiereChannelUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PREMIERE_CHANNEL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String premiereChannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PREMIERE_PROGRAM_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String premiereProgramDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PREMIERE_START_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String premiereStartTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PREMIERE_END_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String premiereEndTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PREMIERE_PALY_URL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String premierePalyUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PREMIERE_REPLAY_URL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String premiereReplayUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.SOUND_CHANNEL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String soundChannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.STATUS_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Date statusDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.LAST_MODIFY_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Date lastModifyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.UPDATE_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.CREATE_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.POSTER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String poster;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.SORT_NUM
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Integer sortNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.ADDR_TYPE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String addrType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.ORG_URL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String orgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.IS3D
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Integer is3d;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.REC_PROGRAM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private Long recProgramId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PROGRAM_RECORD_STATUS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String programRecordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rec_program_content_operate.PROGRAM_DESC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	private String programDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PROGRAM_ID
	 * @return  the value of rec_program_content_operate.PROGRAM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getProgramId() {
		return programId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PROGRAM_ID
	 * @param programId  the value for rec_program_content_operate.PROGRAM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setProgramId(Long programId) {
		this.programId = programId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PROGRAM_NAME
	 * @return  the value of rec_program_content_operate.PROGRAM_NAME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getProgramName() {
		return programName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PROGRAM_NAME
	 * @param programName  the value for rec_program_content_operate.PROGRAM_NAME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setProgramName(String programName) {
		this.programName = programName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.ENGLISH_NAME
	 * @return  the value of rec_program_content_operate.ENGLISH_NAME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.ENGLISH_NAME
	 * @param englishName  the value for rec_program_content_operate.ENGLISH_NAME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.ALIAS
	 * @return  the value of rec_program_content_operate.ALIAS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.ALIAS
	 * @param alias  the value for rec_program_content_operate.ALIAS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.MATERIAL_TYPE_ID
	 * @return  the value of rec_program_content_operate.MATERIAL_TYPE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getMaterialTypeId() {
		return materialTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.MATERIAL_TYPE_ID
	 * @param materialTypeId  the value for rec_program_content_operate.MATERIAL_TYPE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setMaterialTypeId(String materialTypeId) {
		this.materialTypeId = materialTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.MATERIAL_CLASS
	 * @return  the value of rec_program_content_operate.MATERIAL_CLASS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getMaterialClass() {
		return materialClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.MATERIAL_CLASS
	 * @param materialClass  the value for rec_program_content_operate.MATERIAL_CLASS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setMaterialClass(String materialClass) {
		this.materialClass = materialClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.DEFINITION_CODE
	 * @return  the value of rec_program_content_operate.DEFINITION_CODE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getDefinitionCode() {
		return definitionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.DEFINITION_CODE
	 * @param definitionCode  the value for rec_program_content_operate.DEFINITION_CODE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setDefinitionCode(String definitionCode) {
		this.definitionCode = definitionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.ZONE
	 * @return  the value of rec_program_content_operate.ZONE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getZone() {
		return zone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.ZONE
	 * @param zone  the value for rec_program_content_operate.ZONE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setZone(String zone) {
		this.zone = zone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.DIRECTOR
	 * @return  the value of rec_program_content_operate.DIRECTOR
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getDirector() {
		return director;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.DIRECTOR
	 * @param director  the value for rec_program_content_operate.DIRECTOR
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setDirector(String director) {
		this.director = director;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.LEADING_ROLE
	 * @return  the value of rec_program_content_operate.LEADING_ROLE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getLeadingRole() {
		return leadingRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.LEADING_ROLE
	 * @param leadingRole  the value for rec_program_content_operate.LEADING_ROLE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setLeadingRole(String leadingRole) {
		this.leadingRole = leadingRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.YEARS
	 * @return  the value of rec_program_content_operate.YEARS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getYears() {
		return years;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.YEARS
	 * @param years  the value for rec_program_content_operate.YEARS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setYears(String years) {
		this.years = years;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.LANGUAGE_ID
	 * @return  the value of rec_program_content_operate.LANGUAGE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getLanguageId() {
		return languageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.LANGUAGE_ID
	 * @param languageId  the value for rec_program_content_operate.LANGUAGE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setLanguageId(Long languageId) {
		this.languageId = languageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.SET_NUMBER
	 * @return  the value of rec_program_content_operate.SET_NUMBER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getSetNumber() {
		return setNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.SET_NUMBER
	 * @param setNumber  the value for rec_program_content_operate.SET_NUMBER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setSetNumber(Long setNumber) {
		this.setNumber = setNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.BITRATE_ID
	 * @return  the value of rec_program_content_operate.BITRATE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Integer getBitrateId() {
		return bitrateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.BITRATE_ID
	 * @param bitrateId  the value for rec_program_content_operate.BITRATE_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setBitrateId(Integer bitrateId) {
		this.bitrateId = bitrateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.TRIAL_DURA
	 * @return  the value of rec_program_content_operate.TRIAL_DURA
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getTrialDura() {
		return trialDura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.TRIAL_DURA
	 * @param trialDura  the value for rec_program_content_operate.TRIAL_DURA
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setTrialDura(Long trialDura) {
		this.trialDura = trialDura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PROGRAM_STATUS
	 * @return  the value of rec_program_content_operate.PROGRAM_STATUS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getProgramStatus() {
		return programStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PROGRAM_STATUS
	 * @param programStatus  the value for rec_program_content_operate.PROGRAM_STATUS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setProgramStatus(String programStatus) {
		this.programStatus = programStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.RESOLUTION_ID
	 * @return  the value of rec_program_content_operate.RESOLUTION_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Integer getResolutionId() {
		return resolutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.RESOLUTION_ID
	 * @param resolutionId  the value for rec_program_content_operate.RESOLUTION_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setResolutionId(Integer resolutionId) {
		this.resolutionId = resolutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PROGRAM_LENGTH
	 * @return  the value of rec_program_content_operate.PROGRAM_LENGTH
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Integer getProgramLength() {
		return programLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PROGRAM_LENGTH
	 * @param programLength  the value for rec_program_content_operate.PROGRAM_LENGTH
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setProgramLength(Integer programLength) {
		this.programLength = programLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.TAG
	 * @return  the value of rec_program_content_operate.TAG
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.TAG
	 * @param tag  the value for rec_program_content_operate.TAG
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PREMIERE_CHANNEL_UUID
	 * @return  the value of rec_program_content_operate.PREMIERE_CHANNEL_UUID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getPremiereChannelUuid() {
		return premiereChannelUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PREMIERE_CHANNEL_UUID
	 * @param premiereChannelUuid  the value for rec_program_content_operate.PREMIERE_CHANNEL_UUID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setPremiereChannelUuid(String premiereChannelUuid) {
		this.premiereChannelUuid = premiereChannelUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PREMIERE_CHANNEL
	 * @return  the value of rec_program_content_operate.PREMIERE_CHANNEL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getPremiereChannel() {
		return premiereChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PREMIERE_CHANNEL
	 * @param premiereChannel  the value for rec_program_content_operate.PREMIERE_CHANNEL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setPremiereChannel(String premiereChannel) {
		this.premiereChannel = premiereChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PREMIERE_PROGRAM_DATE
	 * @return  the value of rec_program_content_operate.PREMIERE_PROGRAM_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getPremiereProgramDate() {
		return premiereProgramDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PREMIERE_PROGRAM_DATE
	 * @param premiereProgramDate  the value for rec_program_content_operate.PREMIERE_PROGRAM_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setPremiereProgramDate(String premiereProgramDate) {
		this.premiereProgramDate = premiereProgramDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PREMIERE_START_TIME
	 * @return  the value of rec_program_content_operate.PREMIERE_START_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getPremiereStartTime() {
		return premiereStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PREMIERE_START_TIME
	 * @param premiereStartTime  the value for rec_program_content_operate.PREMIERE_START_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setPremiereStartTime(String premiereStartTime) {
		this.premiereStartTime = premiereStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PREMIERE_END_TIME
	 * @return  the value of rec_program_content_operate.PREMIERE_END_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getPremiereEndTime() {
		return premiereEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PREMIERE_END_TIME
	 * @param premiereEndTime  the value for rec_program_content_operate.PREMIERE_END_TIME
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setPremiereEndTime(String premiereEndTime) {
		this.premiereEndTime = premiereEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PREMIERE_PALY_URL
	 * @return  the value of rec_program_content_operate.PREMIERE_PALY_URL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getPremierePalyUrl() {
		return premierePalyUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PREMIERE_PALY_URL
	 * @param premierePalyUrl  the value for rec_program_content_operate.PREMIERE_PALY_URL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setPremierePalyUrl(String premierePalyUrl) {
		this.premierePalyUrl = premierePalyUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PREMIERE_REPLAY_URL
	 * @return  the value of rec_program_content_operate.PREMIERE_REPLAY_URL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getPremiereReplayUrl() {
		return premiereReplayUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PREMIERE_REPLAY_URL
	 * @param premiereReplayUrl  the value for rec_program_content_operate.PREMIERE_REPLAY_URL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setPremiereReplayUrl(String premiereReplayUrl) {
		this.premiereReplayUrl = premiereReplayUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.SOUND_CHANNEL
	 * @return  the value of rec_program_content_operate.SOUND_CHANNEL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getSoundChannel() {
		return soundChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.SOUND_CHANNEL
	 * @param soundChannel  the value for rec_program_content_operate.SOUND_CHANNEL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setSoundChannel(String soundChannel) {
		this.soundChannel = soundChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.STATUS_DATE
	 * @return  the value of rec_program_content_operate.STATUS_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Date getStatusDate() {
		return statusDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.STATUS_DATE
	 * @param statusDate  the value for rec_program_content_operate.STATUS_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.LAST_MODIFY_DATE
	 * @return  the value of rec_program_content_operate.LAST_MODIFY_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Date getLastModifyDate() {
		return lastModifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.LAST_MODIFY_DATE
	 * @param lastModifyDate  the value for rec_program_content_operate.LAST_MODIFY_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.UPDATE_USER
	 * @return  the value of rec_program_content_operate.UPDATE_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.UPDATE_USER
	 * @param updateUser  the value for rec_program_content_operate.UPDATE_USER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.CREATE_DATE
	 * @return  the value of rec_program_content_operate.CREATE_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.CREATE_DATE
	 * @param createDate  the value for rec_program_content_operate.CREATE_DATE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.POSTER
	 * @return  the value of rec_program_content_operate.POSTER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getPoster() {
		return poster;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.POSTER
	 * @param poster  the value for rec_program_content_operate.POSTER
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setPoster(String poster) {
		this.poster = poster;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.SORT_NUM
	 * @return  the value of rec_program_content_operate.SORT_NUM
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Integer getSortNum() {
		return sortNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.SORT_NUM
	 * @param sortNum  the value for rec_program_content_operate.SORT_NUM
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setSortNum(Integer sortNum) {
		this.sortNum = sortNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.ADDR_TYPE
	 * @return  the value of rec_program_content_operate.ADDR_TYPE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getAddrType() {
		return addrType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.ADDR_TYPE
	 * @param addrType  the value for rec_program_content_operate.ADDR_TYPE
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setAddrType(String addrType) {
		this.addrType = addrType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.ORG_URL
	 * @return  the value of rec_program_content_operate.ORG_URL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getOrgUrl() {
		return orgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.ORG_URL
	 * @param orgUrl  the value for rec_program_content_operate.ORG_URL
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setOrgUrl(String orgUrl) {
		this.orgUrl = orgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.IS3D
	 * @return  the value of rec_program_content_operate.IS3D
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Integer getIs3d() {
		return is3d;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.IS3D
	 * @param is3d  the value for rec_program_content_operate.IS3D
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setIs3d(Integer is3d) {
		this.is3d = is3d;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.REC_PROGRAM_ID
	 * @return  the value of rec_program_content_operate.REC_PROGRAM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public Long getRecProgramId() {
		return recProgramId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.REC_PROGRAM_ID
	 * @param recProgramId  the value for rec_program_content_operate.REC_PROGRAM_ID
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setRecProgramId(Long recProgramId) {
		this.recProgramId = recProgramId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PROGRAM_RECORD_STATUS
	 * @return  the value of rec_program_content_operate.PROGRAM_RECORD_STATUS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getProgramRecordStatus() {
		return programRecordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PROGRAM_RECORD_STATUS
	 * @param programRecordStatus  the value for rec_program_content_operate.PROGRAM_RECORD_STATUS
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setProgramRecordStatus(String programRecordStatus) {
		this.programRecordStatus = programRecordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rec_program_content_operate.PROGRAM_DESC
	 * @return  the value of rec_program_content_operate.PROGRAM_DESC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public String getProgramDesc() {
		return programDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rec_program_content_operate.PROGRAM_DESC
	 * @param programDesc  the value for rec_program_content_operate.PROGRAM_DESC
	 * @mbggenerated  Wed Oct 15 14:22:49 CST 2014
	 */
	public void setProgramDesc(String programDesc) {
		this.programDesc = programDesc;
	}

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }
}