---终端历史表
CREATE TABLE `bss_device_history` (
  `id` bigint(19) NOT NULL AUTO_INCREMENT,
  `code` varchar(32) DEFAULT NULL,
  `sno` varchar(32) DEFAULT NULL,
  `mac` varchar(32) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `activate_date` datetime DEFAULT NULL,
  `state_change_date` datetime DEFAULT NULL,
  `expire_date` datetime DEFAULT NULL,
  `state` varchar(32) DEFAULT NULL,
  `bind_type` varchar(32) DEFAULT NULL,
  `distribute_state` varchar(32) DEFAULT NULL,
  `area_id` bigint(19) DEFAULT NULL,
  `device_vendor_id` bigint(19) DEFAULT NULL,
  `device_type_id` bigint(19) DEFAULT NULL,
  `ip_address` varchar(32) DEFAULT NULL,
  `description` varchar(5000) DEFAULT NULL,
  `is_lock` varchar(32) DEFAULT NULL,
  `city_id` bigint(19) DEFAULT NULL,
  `sp_define_id` bigint(19) DEFAULT NULL,
  `product_no` varchar(32) DEFAULT NULL,
  `is_sync` varchar(32) DEFAULT NULL,
  `soft_code` varchar(64) DEFAULT NULL,
  `version_seq` int(11) DEFAULT NULL,
  `ysten_id` varchar(32) DEFAULT NULL,
  `prepare_open` varchar(15) DEFAULT NULL,
  `history_create_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_SNO` (`sno`),
  UNIQUE KEY `IDX_CODE` (`code`) USING BTREE,
  UNIQUE KEY `ysten_id` (`ysten_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8